
# Setup
title: DMI
description: >- # this means to ignore newlines until "baseurl:"
  Discourse Mutual Information
tagline: Discourse Mutual Information
url: https://getpoole.com
paginate: 1
baseurl: DMI/
permalink: pretty

# Build settings
theme: minima
# Gems
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Bishal Santra
  url: https://twitter.com/b_santra
  email: bsantraigi-at-gmail.com

# Custom vars
version: 3.0.0
